### ISSUE TITLE
Medisana BS430

### ISSUE THREAD

**Issue by cscherpenisse** [bwynants/weegschaal#2]
First of all, thank you for creating an ESP-Home version for the Medisana scale.

I have a Medisana BS430 scale.
This now works properly via the integration of https://github.com/keptenkurk/BS440 on a Raspberry pi Zero W

I have now transferred this with your integration with esp home to an ESP32.
The BS430 does connect, but only transmits the data below, and not the weight, fat and other data.
[MedisanaBS444:233] data Person: 1; gender: male; age: 32; size: 1.89; activity: normal:

Is there a difference in the protocols? Or can I add the right type of scale somewhere?

**Comment by bwynants** [comment]
can you make a trace?

```
logger:
  level: DEBUG

```

**Comment by CSC9110** [comment]
[BS430 Log.txt](https://github.com/bwynants/weegschaal/files/13853942/BS430.Log.txt)
See attached log file.
This is the connection with the scale from the start and until the connection is broken.
Hopefully you can see something from this.

**Comment by bwynants** [comment]
can you try this?
change in the external_components definition

`     ref: main
`
into 
`     ref: zero-offset
`

**Comment by CSC9110** [comment]
[BS430Log1.txt](https://github.com/bwynants/weegschaal/files/13857583/BS430Log1.txt)
See attached log file.
Nothing seems to have changed.
In any case, thanks for your thoughts.

**Comment by CSC9110** [comment]
I tested it but without good results.
The Raspberry Pi Zero was turned off.
I'll try to find out for myself soon.

The device name is not necessary?

**Comment by CSC9110** [comment]
I would like to do a test with the Branche"ESP32-BLE-Arduino".
How did you load this onto the ESP32?
Via Arduino Editor?

**Comment by bwynants** [comment]
> I would like to do a test with the Branche"ESP32-BLE-Arduino".
> How did you load this onto the ESP32?
> Via Arduino Editor?

just the same, via ESPHome, and most probably i was connected directly  to the computer (not OTA) it is a big file and i needed to disabled unneeded components....

yaml in that branch should work.

**Comment by CSC9110** [comment]
The branch "ESP32-BLE-Arduino"works fine for the Medisana BS430
Thank you!

**Comment by jondiez** [comment]
Hello, I have the same problem, only the data appears:
[MedisanaBS444:237]: data Person: 1; gender: male; age: 44; size: 1.81; activity: high:
I have compiled it to an ESP32 with esphome flasher, discovered the MAC and it does not load any more data. I also tried changing ref: zero-offset, but the result is the same. I also have a BS430 and I don't understand how my colleague solved it with ESP32-BLE-Arduino.
Please, could you help me?
Thank you

**Comment by jondiez** [comment]
> La rama "ESP32-BLE-Arduino" funciona bien para el Medisana BS430 ¡Gracias!

Could you tell me how you got it? I'm not very good with Arduino IDE

**Comment by CSC9110** [comment]
> > La rama "ESP32-BLE-Arduino" funciona bien para el Medisana BS430 ¡Gracias!
> 
> Could you tell me how you got it? I'm not very good with Arduino IDE

I saved the files locally in Home Assistant, and then uploaded them via Esp Home.

**Comment by jondiez** [comment]
> > > La rama "ESP32-BLE-Arduino" funciona bien para el Medisana BS430 ¡Gracias!
> > 
> > 
> > ¿Podrías decirme cómo lo conseguiste? No soy muy bueno con Arduino IDE
> 
> Guardé los archivos localmente en Home Assistant y luego los subí a través de Esp Home.

Sorry, what files did you save?  I have Esphome through HACS, I have no add-ons.  Could you give more details please, let's see if I can find it.

**Comment by jondiez** [comment]
> > > > > La rama "ESP32-BLE-Arduino" funciona bien para el Medisana BS430 ¡Gracias!
> > > > 
> > > > 
> > > > ¿Podrías decirme cómo lo conseguiste? No soy muy bueno con Arduino IDE
> > > 
> > > 
> > > Guardé los archivos localmente en Home Assistant y luego los subí a través de Esp Home.
> > 
> > 
> > Lo siento, ¿qué archivos guardaste? Tengo Esphome a través de HACS, no tengo complementos. ¿Podrías dar más detalles por favor? A ver si puedo encontrarlo.
> 
> Si lo guardas así funciona: homeassistant/esphome/lib/scale/

Sorry, I don't understand, what files do I keep there?  And how do I keep them there?  Is it possible only from HA supervisor or with add-ons?  I have HACS and I don't know if the files can be saved that way.  Could you please detail more?

**Comment by CSC9110** [comment]
> > > > > > La rama "ESP32-BLE-Arduino" funciona bien para el Medisana BS430 ¡Gracias!
> > > > > 
> > > > > 
> > > > > ¿Podrías decirme cómo lo conseguiste? No soy muy bueno con Arduino IDE
> > > > 
> > > > 
> > > > Guardé los archivos localmente en Home Assistant y luego los subí a través de Esp Home.
> > > 
> > > 
> > > Lo siento, ¿qué archivos guardaste? Tengo Esphome a través de HACS, no tengo complementos. ¿Podrías dar más detalles por favor? A ver si puedo encontrarlo.
> > 
> > 
> > Si lo guardas así funciona: homeassistant/esphome/lib/scale/
> 
> Sorry, I don't understand, what files do I keep there? And how do I keep them there? Is it possible only from HA supervisor or with add-ons? I have HACS and I don't know if the files can be saved that way. Could you please detail more?

See image below for details.
If you don't know how to get the files into homeassistant, there are plenty of manuals available on Google. 
It's also a bit of trial and error :)
![image](https://github.com/bwynants/weegschaal/assets/117529571/72153cbb-cf98-4d36-a4c3-677a300928a3)

**Comment by jondiez** [comment]
> > > > > La rama "ESP32-BLE-Arduino" funciona bien para el Medisana BS430 ¡Gracias!
> > > > 
> > > > 
> > > > ¿Podrías decirme cómo lo conseguiste? No soy muy bueno con Arduino IDE
> > > 
> > > 
> > > Guardé los archivos localmente en Home Assistant y luego los subí a través de Esp Home.
> > 
> > 
> > Sorry, what files did you save? I have Esphome through HACS, I have no add-ons. Could you give more details please, let's see if I can find it.
> 
> If you save it like this it works: homeassistant/esphome/lib/scale/

Thanks, but I don't have that folder inside homeassistant.  I use HACS and I am with docker.  I've been looking at both the HA and Esphome folders and I can't find that lib folder.  Would you know where I can look for it?

**Comment by CSC9110** [comment]
> > > > > > La rama "ESP32-BLE-Arduino" funciona bien para el Medisana BS430 ¡Gracias!
> > > > > 
> > > > > 
> > > > > ¿Podrías decirme cómo lo conseguiste? No soy muy bueno con Arduino IDE
> > > > 
> > > > 
> > > > Guardé los archivos localmente en Home Assistant y luego los subí a través de Esp Home.
> > > 
> > > 
> > > Sorry, what files did you save? I have Esphome through HACS, I have no add-ons. Could you give more details please, let's see if I can find it.
> > 
> > 
> > If you save it like this it works: homeassistant/esphome/lib/scale/
> 
> Thanks, but I don't have that folder inside homeassistant. I use HACS and I am with docker. I've been looking at both the HA and Esphome folders and I can't find that lib folder. Would you know where I can look for it?

You can use Config editor via HACS. You can simply add folders that do not exist manually.

**Comment by bwynants** [comment]
> Thank you. So I can create the folder in home assistant (homeassistant/esphome/lib/scale/) and add those files to it?

You should make that folder where the yaml file is created when you add a "new device" to esphome

**Comment by bwynants** [comment]
> Thank you. So I can create the folder in home assistant (homeassistant/esphome/lib/scale/) and add those files to it?

I made it a bit easier. Have a look at this for instructions, no need to copy files anymore
https://github.com/bwynants/weegschaal/tree/ESP32-BLE-Arduino

**Comment by cscherpenisse** [comment]
Thanks for the adjustments.

I don't know if it's possible but I would like a switch in Home Assistant that would allow me to start and stop the Bluetooth scanner between certain times.
Now it is always scanning, is this easy to add?

**Comment by jondiez** [comment]
> > Thank you. So I can create the folder in home assistant (homeassistant/esphome/lib/scale/) and add those files to it?
> 
> I made it a bit easier. Have a look at this for instructions, no need to copy files anymore https://github.com/bwynants/weegschaal/tree/ESP32-BLE-Arduino

Working.  Thank you very much for your enormous work and the quick response.

**Comment by bwynants** [comment]
> Thanks for the adjustments.
> 
> I don't know if it's possible but I would like a switch in Home Assistant that would allow me to start and stop the Bluetooth scanner between certain times. Now it is always scanning, is this easy to add?

you can add an optional switch to the yams now do disable scanning, not sure if it is useful but it is optional so....

**Comment by bwynants** [comment]
closed

**Comment by cscherpenisse** [comment]
> > Thanks for the adjustments.
> > I don't know if it's possible but I would like a switch in Home Assistant that would allow me to start and stop the Bluetooth scanner between certain times. Now it is always scanning, is this easy to add?
> 
> you can add an optional switch to the yaml now do disable scanning, not sure if it is useful but it is optional so....

Thanks, I tested it and it works.
